CREATE TABLE TB_ROLE (
  ID SERIAL PRIMARY KEY,
  ROLE_NAME VARCHAR(20) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_USER (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(40),
  USERNAME VARCHAR(15) UNIQUE NOT NULL,
  EMAIL VARCHAR(40) UNIQUE NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_USER_TB_ROLE (
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  CONSTRAINT USER_ROLE_USER_ID_FKEY FOREIGN KEY (USER_ID)
      REFERENCES TB_USER (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT USER_ROLE_ROLE_ID_FKEY FOREIGN KEY (ROLE_ID)
      REFERENCES TB_ROLE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  PRIMARY KEY (USER_ID, ROLE_ID)
);

INSERT INTO TB_ROLE(ROLE_NAME) VALUES('ROLE_USER');
INSERT INTO TB_ROLE(ROLE_NAME) VALUES('ROLE_ADMIN');