version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: finanzium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    ports:
      - "5432:5432"